package com.petclinic.vet.mapper;

import com.petclinic.vet.dto.SpecialtyDto;
import com.petclinic.vet.entity.Specialty;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** Integration test for SpecialtyMapper (generated by MapStruct) to verify entity-to-DTO mapping. */
@SpringBootTest
class SpecialtyMapperTest {

    @Autowired
    private SpecialtyMapper mapper;

    @Test
    void toDto_mapsFields() {
        Specialty entity = new Specialty();
        entity.setId(5);
        entity.setName("surgery");

        SpecialtyDto dto = mapper.toDto(entity);

        assertThat(dto.id()).isEqualTo(5);
        assertThat(dto.name()).isEqualTo("surgery");
    }

    @Test
    void toDto_null_returnsNull() {
        assertThat(mapper.toDto(null)).isNull();
    }

    @Test
    void toEntity_mapsFields() {
        SpecialtyDto dto = new SpecialtyDto(5, "surgery");

        Specialty entity = mapper.toEntity(dto);

        assertThat(entity.getId()).isEqualTo(5);
        assertThat(entity.getName()).isEqualTo("surgery");
    }

    @Test
    void toEntity_null_returnsNull() {
        assertThat(mapper.toEntity(null)).isNull();
    }

    @Test
    void toDtoList_mapsList() {
        Specialty s1 = new Specialty();
        s1.setId(1);
        s1.setName("a");

        Specialty s2 = new Specialty();
        s2.setId(2);
        s2.setName("b");

        List<SpecialtyDto> dtos = mapper.toDtoList(List.of(s1, s2));
        assertThat(dtos).hasSize(2);
    }

    @Test
    void toDtoList_null_returnsNull() {
        assertThat(mapper.toDtoList(null)).isNull();
    }

    @Test
    void updateEntity_updatesName() {
        Specialty entity = new Specialty();
        entity.setId(1);
        entity.setName("old");

        SpecialtyDto dto = new SpecialtyDto(1, "new-name");
        mapper.updateEntity(dto, entity);

        assertThat(entity.getName()).isEqualTo("new-name");
        assertThat(entity.getId()).isEqualTo(1);
    }

    @Test
    void updateEntity_nullDto_noOp() {
        Specialty entity = new Specialty();
        entity.setId(1);
        entity.setName("original");

        mapper.updateEntity(null, entity);
        assertThat(entity.getName()).isEqualTo("original");
    }
}
