package com.petclinic.vet.mapper;

import com.petclinic.vet.dto.SpecialtyDto;
import com.petclinic.vet.dto.VetDto;
import com.petclinic.vet.entity.Specialty;
import com.petclinic.vet.entity.Vet;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/** Integration test for VetMapper (generated by MapStruct) to verify entity-to-DTO mapping. */
@SpringBootTest
class VetMapperTest {

    @Autowired
    private VetMapper vetMapper;

    @Test
    void toDto_mapsAllFields() {
        Specialty s = new Specialty();
        s.setId(1);
        s.setName("radiology");

        Vet vet = new Vet();
        vet.setId(10);
        vet.setFirstName("James");
        vet.setLastName("Carter");
        vet.setSpecialties(Set.of(s));

        VetDto dto = vetMapper.toDto(vet);

        assertThat(dto.id()).isEqualTo(10);
        assertThat(dto.firstName()).isEqualTo("James");
        assertThat(dto.lastName()).isEqualTo("Carter");
        assertThat(dto.specialties()).hasSize(1);
        assertThat(dto.specialties().get(0).name()).isEqualTo("radiology");
    }

    @Test
    void toDto_nullVet_returnsNull() {
        assertThat(vetMapper.toDto(null)).isNull();
    }

    @Test
    void toDtoList_mapsAllVets() {
        Vet v1 = new Vet();
        v1.setId(1);
        v1.setFirstName("A");
        v1.setLastName("B");
        v1.setSpecialties(new HashSet<>());

        Vet v2 = new Vet();
        v2.setId(2);
        v2.setFirstName("C");
        v2.setLastName("D");
        v2.setSpecialties(new HashSet<>());

        List<VetDto> dtos = vetMapper.toDtoList(List.of(v1, v2));
        assertThat(dtos).hasSize(2);
    }

    @Test
    void toDtoList_null_returnsNull() {
        assertThat(vetMapper.toDtoList(null)).isNull();
    }

    @Test
    void specialtiesToDtoList_nullSet_returnsEmpty() {
        List<SpecialtyDto> result = vetMapper.specialtiesToDtoList(null);
        assertThat(result).isEmpty();
    }

    @Test
    void specialtiesToDtoList_multipleSpecialties_sortedById() {
        Specialty s1 = new Specialty();
        s1.setId(3);
        s1.setName("dentistry");

        Specialty s2 = new Specialty();
        s2.setId(1);
        s2.setName("radiology");

        List<SpecialtyDto> result = vetMapper.specialtiesToDtoList(Set.of(s1, s2));
        assertThat(result).hasSize(2);
        assertThat(result.get(0).id()).isEqualTo(1);
        assertThat(result.get(1).id()).isEqualTo(3);
    }

    @Test
    void specialtiesToDtoList_specialtyWithNullId_handled() {
        Specialty s = new Specialty();
        s.setName("unknown");

        List<SpecialtyDto> result = vetMapper.specialtiesToDtoList(Set.of(s));
        assertThat(result).hasSize(1);
        assertThat(result.get(0).name()).isEqualTo("unknown");
    }

    @Test
    void toDto_emptySpecialties_returnsEmptyList() {
        Vet vet = new Vet();
        vet.setId(1);
        vet.setFirstName("A");
        vet.setLastName("B");
        vet.setSpecialties(new HashSet<>());

        VetDto dto = vetMapper.toDto(vet);
        assertThat(dto.specialties()).isEmpty();
    }

    @Test
    void toDto_nullSpecialties_returnsEmptyList() {
        Vet vet = new Vet();
        vet.setId(1);
        vet.setFirstName("A");
        vet.setLastName("B");
        vet.setSpecialties(null);

        VetDto dto = vetMapper.toDto(vet);
        assertThat(dto.specialties()).isEmpty();
    }
}
