spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

logging:
  level:
    com.petclinic.vet: WARN
    org.springframework.web: WARN

management:
  endpoint:
    health:
      show-details: never
